### ISSUE TITLE
figure out why tests fail locally

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#12]
but run fine on travis...

```
$ grunt test
Running "env:test" (env) task

Running "jshint:all" (jshint) task
>> 53 files lint free.

Running "nodeunit:all" (nodeunit) task
Testing audit-proxy.js....OK
Testing auth.js.........OK
Testing active-pregnancies.js....OK
Testing delivery-location.js..OK
Testing export-data.js..................OK
Testing fti.js..........OK
Testing high-risk.js.....OK
Testing messages.js.......OK
Testing missed-appointments.js......OK
Testing missing-delivery-reports.js....OK
Testing monthly-deliveries.js..F
>> get returns monthly deliveries count
>> Actual:
>>   [ { month: 'Dec 1968', count: 0 },
>>     { month: 'Jan 1969', count: 0 },
>>     { month: 'Feb 1969', count: 0 },
>>     { month: 'Mar 1969', count: 1 },
>>     { month: 'Apr 1969', count: 0 },
>>     { month: 'May 1969', count: 0 },
>>     { month: 'Jun 1969', count: 2 },
>>     { month: 'Jul 1969', count: 0 },
>>     { month: 'Aug 1969', count: 0 },
>>     { month: 'Sep 1969', count: 1 },
>>     { month: 'Oct 1969', count: 0 },
>>     { month: 'Nov 1969', count: 0 } ]
>> Operator:
>>   deepEqual
>> Expected:
>>   [ { month: 'Jan 1969', count: 0 },
>>     { month: 'Feb 1969', count: 0 },
>>     { month: 'Mar 1969', count: 1 },
>>     { month: 'Apr 1969', count: 0 },
>>     { month: 'May 1969', count: 0 },
>>     { month: 'Jun 1969', count: 2 },
>>     { month: 'Jul 1969', count: 0 },
>>     { month: 'Aug 1969', count: 0 },
>>     { month: 'Sep 1969', count: 1 },
>>     { month: 'Oct 1969', count: 0 },
>>     { month: 'Nov 1969', count: 0 },
>>     { month: 'Dec 1969', count: 0 } ]
>> at /Users/mandric/dev/medic-api/tests/controllers/monthly-deliveries.js:117:10
>> at /Users/mandric/dev/medic-api/controllers/monthly-deliveries.js:78:9
>> at /Users/mandric/dev/medic-api/controllers/monthly-deliveries.js:60:5
>> at /Users/mandric/dev/medic-api/controllers/utils.js:39:5
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)

Testing monthly-registrations.js.F
>> get returns monthly registrations count
>> Actual:
>>   [ { month: 'Dec 1968', count: 0 },
>>     { month: 'Jan 1969', count: 0 },
>>     { month: 'Feb 1969', count: 0 },
>>     { month: 'Mar 1969', count: 0 },
>>     { month: 'Apr 1969', count: 0 },
>>     { month: 'May 1969', count: 0 },
>>     { month: 'Jun 1969', count: 0 },
>>     { month: 'Jul 1969', count: 0 },
>>     { month: 'Aug 1969', count: 0 },
>>     { month: 'Sep 1969', count: 1 },
>>     { month: 'Oct 1969', count: 0 },
>>     { month: 'Nov 1969', count: 2 } ]
>> Operator:
>>   deepEqual
>> Expected:
>>   [ { month: 'Jan 1969', count: 0 },
>>     { month: 'Feb 1969', count: 0 },
>>     { month: 'Mar 1969', count: 0 },
>>     { month: 'Apr 1969', count: 0 },
>>     { month: 'May 1969', count: 0 },
>>     { month: 'Jun 1969', count: 0 },
>>     { month: 'Jul 1969', count: 0 },
>>     { month: 'Aug 1969', count: 0 },
>>     { month: 'Sep 1969', count: 0 },
>>     { month: 'Oct 1969', count: 1 },
>>     { month: 'Nov 1969', count: 0 },
>>     { month: 'Dec 1969', count: 2 } ]
>> at /Users/mandric/dev/medic-api/tests/controllers/monthly-registrations.js:60:10
>> at /Users/mandric/dev/medic-api/controllers/monthly-registrations.js:47:7
>> at /Users/mandric/dev/medic-api/controllers/utils.js:39:5
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at Object.fti (controllers/utils.js:30:6)

Testing total-births.js...OK
Testing upcoming-appointments.js.......OK
Testing upcoming-due-dates.js....OK
Testing utils.js....OK
Testing visits-complete.js.....OK
Testing visits-during.js.......OK
Testing migrations.js..Migration "xyz" completed successfully
.Migration "xyz" completed successfully
Migration "abc" completed successfully
.Migration "a" completed successfully
.Migration "xyz" completed successfully
.OK
Testing extract-person-contacts.js....OK
Testing stats-submission.js..........OK
Testing usage-stats.js..F
>> go saves a doc with results
>> Actual:
>>   { startkey: [ 1969, 10 ],
>>     endkey: [ 1969, 10, {} ] }
>> Operator:
>>   deepEqual
>> Expected:
>>   { startkey: [ 1969, 11 ],
>>     endkey: [ 1969, 11, {} ] }
>> at /Users/mandric/dev/medic-api/tests/schedules/usage-stats.js:115:10
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at /Users/mandric/dev/medic-api/schedules/usage-stats.js:157:22
>> at /Users/mandric/dev/medic-api/node_modules/async/lib/async.js:592:17
>> at done (node_modules/async/lib/async.js:135:19)

>> go saves a doc with results
>> Actual:
>>   { group: true,
>>     startkey: [ 1969, 10 ],
>>     endkey: [ 1969, 10, {} ] }
>> Operator:
>>   deepEqual
>> Expected:
>>   { group: true,
>>     startkey: [ 1969, 11 ],
>>     endkey: [ 1969, 11, {} ] }
>> at /Users/mandric/dev/medic-api/tests/schedules/usage-stats.js:120:10
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at /Users/mandric/dev/medic-api/schedules/usage-stats.js:157:22
>> at /Users/mandric/dev/medic-api/node_modules/async/lib/async.js:592:17
>> at done (node_modules/async/lib/async.js:135:19)

>> go saves a doc with results
>> Actual:
>>   { group: true,
>>     startkey: [ 1969, 10 ],
>>     endkey: [ 1969, 10, {} ] }
>> Operator:
>>   deepEqual
>> Expected:
>>   { group: true,
>>     startkey: [ 1969, 11 ],
>>     endkey: [ 1969, 11, {} ] }
>> at /Users/mandric/dev/medic-api/tests/schedules/usage-stats.js:126:10
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at /Users/mandric/dev/medic-api/schedules/usage-stats.js:157:22
>> at /Users/mandric/dev/medic-api/node_modules/async/lib/async.js:592:17
>> at done (node_modules/async/lib/async.js:135:19)

>> go saves a doc with results
>> Actual:
>>   { group: true,
>>     startkey: [ 1969, 10 ],
>>     endkey: [ 1969, 10, {} ] }
>> Operator:
>>   deepEqual
>> Expected:
>>   { group: true,
>>     startkey: [ 1969, 11 ],
>>     endkey: [ 1969, 11, {} ] }
>> at /Users/mandric/dev/medic-api/tests/schedules/usage-stats.js:132:10
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at /Users/mandric/dev/medic-api/schedules/usage-stats.js:157:22
>> at /Users/mandric/dev/medic-api/node_modules/async/lib/async.js:592:17
>> at done (node_modules/async/lib/async.js:135:19)

>> go saves a doc with results
>> Actual:
>>   { valid_form_submissions: { R: 23, V: 5 },
>>     delivery_locations: { F: 12, S: 2, NS: 1 },
>>     active_facilities: 3,
>>     visits_per_delivery: 
>>      { '1+': 2,
>>        '2+': 1,
>>        '3+': 1,
>>        '4+': 0 },
>>     estimated_deliveries: 3,
>>     type: 'usage_stats',
>>     generated_date: '1970-01-01T00:00:00.000Z',
>>     year: 1969,
>>     month: 10 }
>> Operator:
>>   deepEqual
>> Expected:
>>   { type: 'usage_stats',
>>     generated_date: '1970-01-01T00:00:00.000Z',
>>     month: 11,
>>     year: 1969,
>>     valid_form_submissions: { R: 23, V: 5 },
>>     delivery_locations: { F: 12, S: 2, NS: 1 },
>>     active_facilities: 3,
>>     visits_per_delivery: 
>>      { '1+': 2,
>>        '2+': 1,
>>        '3+': 1,
>>        '4+': 0 },
>>     estimated_deliveries: 3 }
>> at /Users/mandric/dev/medic-api/tests/schedules/usage-stats.js:146:10
>> at callCallback (node_modules/sinon/lib/sinon/behavior.js:117:26)
>> at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:140:17)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:81:61)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:172:59)
>> at Object.proxy (eval at createProxy (node_modules/sinon/lib/sinon/spy.js:79:86), <anonymous>:1:39)
>> at /Users/mandric/dev/medic-api/schedules/usage-stats.js:157:22
>> at /Users/mandric/dev/medic-api/node_modules/async/lib/async.js:592:17
>> at done (node_modules/async/lib/async.js:135:19)

Testing translations.js........OK
Warning: 7/528 assertions failed (921ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by garethbowen** [comment]
Fixed.

**Comment by alxndrsn** [comment]
Re-opened - https://github.com/medic/medic-api/issues/29#issuecomment-131716773

**Comment by garethbowen** [comment]
@alxndrsn Could you try again with this latest patch? If it doesn't work I'd appreciate another set of eyes - it's hard to fix now that it's passing in NZ...

**Comment by alxndrsn** [comment]
Works on my machine!
